services:
  frontend:
    image: ghcr.io/juliyasg/film-frontend:latest
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/dist
    command: sh -c "cp -r /app/dist/* /dist && tail -f /dev/null"

  backend:
    image: ghcr.io/juliyasg/film-backend:latest
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: nest_project
      DATABASE_USERNAME: student
      DATABASE_PASSWORD: student
      DATABASE_DRIVER: postgres
      LOGGER_FORMAT: dev
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  nginx:
    image: ghcr.io/juliyasg/film-nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: film_postgres
    environment:
      POSTGRES_DB: nest_project
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: film_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  frontend_dist:
  postgres_data:
  pgadmin_data: